export const dummyData = [
  // Delhi - 100K - 200K
  {
    propertyType: "House",
    location: "Delhi",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 1,
        price: "150K",
        name: "Beautiful Home in Delhi 1",
        address: "123 Main Street, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 2,
        price: "170K",
        name: "Charming House in Delhi 2",
        address: "456 Park Avenue, Delhi",
        beds: 2,
        bathroom: 1,
        area: "1200 sqft",
        image: "https://example.com/property2.jpg",
      },
      {
        id: 3,
        price: "180K",
        name: "Cozy Home in Delhi 3",
        address: "789 Elm Street, Delhi",
        beds: 2,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/property3.jpg",
      },
      {
        id: 4,
        price: "190K",
        name: "Modern House in Delhi 4",
        address: "101 Maple Avenue, Delhi",
        beds: 4,
        bathroom: 3,
        area: "1800 sqft",
        image: "https://example.com/property4.jpg",
      },
    ],
  },

  // Delhi - 200K - 300K
  {
    propertyType: "House",
    location: "Delhi",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 5,
        price: "220K",
        name: "Spacious Home in Delhi 5",
        address: "111 Oak Street, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property5.jpg",
      },
      {
        id: 6,
        price: "250K",
        name: "Modern House in Delhi 6",
        address: "222 Maple Avenue, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 7,
        price: "270K",
        name: "Elegant Home in Delhi 7",
        address: "333 Elm Street, Delhi",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image: "https://example.com/property7.jpg",
      },
      {
        id: 8,
        price: "290K",
        name: "Charming House in Delhi 8",
        address: "444 Pine Road, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property8.jpg",
      },
    ],
  },

  // Delhi - 300K - 400K
  {
    propertyType: "House",
    location: "Delhi",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 9,
        price: "320K",
        name: "Spacious Home in Delhi 9",
        address: "555 Oak Lane, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property9.jpg",
      },
      {
        id: 10,
        price: "350K",
        name: "Modern House in Delhi 10",
        address: "666 Maple Road, Delhi",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 11,
        price: "370K",
        name: "Elegant Home in Delhi 11",
        address: "777 Elm Avenue, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property11.jpg",
      },
      {
        id: 12,
        price: "390K",
        name: "Charming House in Delhi 12",
        address: "888 Pine Street, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property12.jpg",
      },
    ],
  },

  // Delhi - 400K - 500K
  {
    propertyType: "House",
    location: "Delhi",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 13,
        price: "420K",
        name: "Spacious Home in Delhi 13",
        address: "999 Oak Avenue, Delhi",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 14,
        price: "450K",
        name: "Modern House in Delhi 14",
        address: "1010 Maple Street, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property14.jpg",
      },
      {
        id: 15,
        price: "470K",
        name: "Elegant Home in Delhi 15",
        address: "1111 Elm Lane, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 16,
        price: "490K",
        name: "Charming House in Delhi 16",
        address: "1212 Pine Avenue, Delhi",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property16.jpg",
      },
    ],
  },
  // ...repeat for the other price ranges in Delhi

  // Mumbai 100K - 200K
  {
    propertyType: "House",
    location: "Mumbai",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 9,
        price: "120K",
        name: "Compact House in Mumbai 1",
        address: "123 Sea View Road, Mumbai",
        beds: 2,
        bathroom: 1,
        area: "1000 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 10,
        price: "180K",
        name: "Stylish Home in Mumbai 2",
        address: "456 Palm Avenue, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/property10.jpg",
      },
      {
        id: 11,
        price: "160K",
        name: "Quaint House in Mumbai 3",
        address: "789 Shoreline Drive, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/property11.jpg",
      },
      {
        id: 12,
        price: "190K",
        name: "Elegant Home in Mumbai 4",
        address: "101 Sunset Blvd, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "1800 sqft",
        image: "https://example.com/property12.jpg",
      },
    ],
  },
  // Mumbai - 200K - 300K
  {
    propertyType: "House",
    location: "Mumbai",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 29,
        price: "220K",
        name: "Elegant House in Mumbai 29",
        address: "123 Ocean Drive, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property29.jpg",
      },
      {
        id: 30,
        price: "250K",
        name: "Luxurious Home in Mumbai 30",
        address: "456 Sunset Lane, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property30.jpg",
      },
      {
        id: 31,
        price: "270K",
        name: "Spacious House in Mumbai 31",
        address: "789 Seafront Road, Mumbai",
        beds: 5,
        bathroom: 4,
        area: "2400 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 32,
        price: "290K",
        name: "Charming Home in Mumbai 32",
        address: "101 Coastal Avenue, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property32.jpg",
      },
    ],
  },

  // Mumbai - 300K - 400K
  {
    propertyType: "House",
    location: "Mumbai",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 33,
        price: "320K",
        name: "Elegant House in Mumbai 33",
        address: "111 Bay Street, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 34,
        price: "350K",
        name: "Luxurious Home in Mumbai 34",
        address: "222 Shoreline Lane, Mumbai",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image: "https://example.com/property34.jpg",
      },
      {
        id: 35,
        price: "370K",
        name: "Spacious House in Mumbai 35",
        address: "333 Beach Road, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property35.jpg",
      },
      {
        id: 36,
        price: "390K",
        name: "Charming Home in Mumbai 36",
        address: "444 Oceanfront Avenue, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property36.jpg",
      },
    ],
  },

  // Mumbai - 400K - 500K
  {
    propertyType: "House",
    location: "Mumbai",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 37,
        price: "420K",
        name: "Elegant House in Mumbai 37",
        address: "555 Waterfront Road, Mumbai",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 38,
        price: "450K",
        name: "Luxurious Home in Mumbai 38",
        address: "666 Seaside Lane, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property38.jpg",
      },
      {
        id: 39,
        price: "470K",
        name: "Spacious House in Mumbai 39",
        address: "777 Ocean Avenue, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property39.jpg",
      },
      {
        id: 40,
        price: "490K",
        name: "Charming Home in Mumbai 40",
        address: "888 Bay Lane, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property40.jpg",
      },
    ],
  },

  // Chennai
  {
    propertyType: "House",
    location: "Chennai",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 17,
        price: "180K",
        name: "Modern Home in Chennai 1",
        address: "123 Marina Street, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1600 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 18,
        price: "190K",
        name: "Charming House in Chennai 2",
        address: "456 Garden Lane, Chennai",
        beds: 2,
        bathroom: 1,
        area: "1300 sqft",
        image: "https://example.com/property18.jpg",
      },
      {
        id: 19,
        price: "150K",
        name: "Cozy Home in Chennai 3",
        address: "789 Oasis Road, Chennai",
        beds: 2,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/property19.jpg",
      },
      {
        id: 20,
        price: "170K",
        name: "Traditional House in Chennai 4",
        address: "101 Lotus Street, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1600 sqft",
        image: "https://example.com/property20.jpg",
      },
    ],
  },
  // Chennai - 200K - 300K
  {
    propertyType: "House",
    location: "Chennai",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 45,
        price: "220K",
        name: "Elegant House in Chennai 45",
        address: "111 Oceanfront Lane, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 46,
        price: "250K",
        name: "Luxurious Home in Chennai 46",
        address: "222 Beach Drive, Chennai",
        beds: 5,
        bathroom: 4,
        area: "2400 sqft",
        image: "https://example.com/property46.jpg",
      },
      {
        id: 47,
        price: "270K",
        name: "Spacious House in Chennai 47",
        address: "333 Coastal Avenue, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property47.jpg",
      },
      {
        id: 48,
        price: "290K",
        name: "Charming Home in Chennai 48",
        address: "444 Shoreline Road, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property48.jpg",
      },
    ],
  },

  // Chennai - 300K - 400K
  {
    propertyType: "House",
    location: "Chennai",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 49,
        price: "320K",
        name: "Elegant House in Chennai 49",
        address: "555 Beachfront Lane, Chennai",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 50,
        price: "350K",
        name: "Luxurious Home in Chennai 50",
        address: "666 Ocean Road, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property50.jpg",
      },
      {
        id: 51,
        price: "370K",
        name: "Spacious House in Chennai 51",
        address: "777 Shoreline Avenue, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property51.jpg",
      },
      {
        id: 52,
        price: "390K",
        name: "Charming Home in Chennai 52",
        address: "888 Coastal Lane, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property52.jpg",
      },
    ],
  },
  // Chennai - 400K - 500K
  {
    propertyType: "House",
    location: "Chennai",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 53,
        price: "420K",
        name: "Elegant House in Chennai 53",
        address: "999 Oceanfront Road, Chennai",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 54,
        price: "450K",
        name: "Luxurious Home in Chennai 54",
        address: "1010 Beach Drive, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property54.jpg",
      },
      {
        id: 55,
        price: "470K",
        name: "Spacious House in Chennai 55",
        address: "1111 Shoreline Avenue, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property55.jpg",
      },
      {
        id: 56,
        price: "490K",
        name: "Charming Home in Chennai 56",
        address: "1212 Coastal Lane, Chennai",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property56.jpg",
      },
    ],
  },

  // Kolkata 100K - 200K
  {
    propertyType: "House",
    location: "Kolkata",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 25,
        price: "140K",
        name: "Charming House in Kolkata 1",
        address: "123 Garden Road, Kolkata",
        beds: 2,
        bathroom: 1,
        area: "1200 sqft",
        image: "https://example.com/property25.jpg",
      },
      {
        id: 26,
        price: "160K",
        name: "Cozy Home in Kolkata 2",
        address: "456 Blossom Lane, Kolkata",
        beds: 2,
        bathroom: 2,
        area: "1300 sqft",
        image: "https://example.com/property26.jpg",
      },
      {
        id: 27,
        price: "170K",
        name: "Modern House in Kolkata 3",
        address: "789 Harmony Street, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/property27.jpg",
      },
      {
        id: 28,
        price: "180K",
        name: "Spacious House in Kolkata 4",
        address: "101 Symphony Avenue, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1600 sqft",
        image: "https://example.com/property28.jpg",
      },
    ],
  },
  // Kolkata 200K - 300K
  {
    propertyType: "House",
    location: "Kolkata",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 61,
        price: "220K",
        name: "Elegant House in Kolkata 61",
        address: "111 Maple Street, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property61.jpg",
      },
      {
        id: 62,
        price: "250K",
        name: "Luxurious Home in Kolkata 62",
        address: "222 Elm Avenue, Kolkata",
        beds: 5,
        bathroom: 4,
        area: "2400 sqft",
        image: "https://example.com/property62.jpg",
      },
      {
        id: 63,
        price: "270K",
        name: "Spacious House in Kolkata 63",
        address: "333 Oak Lane, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property63.jpg",
      },
      {
        id: 64,
        price: "290K",
        name: "Charming Home in Kolkata 64",
        address: "444 Pine Avenue, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
    ],
  },

  // Kolkata - 300K - 400K
  {
    propertyType: "House",
    location: "Kolkata",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 65,
        price: "320K",
        name: "Elegant House in Kolkata 65",
        address: "555 Beach Drive, Kolkata",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image: "https://example.com/property65.jpg",
      },
      {
        id: 66,
        price: "350K",
        name: "Luxurious Home in Kolkata 66",
        address: "666 Ocean Road, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property66.jpg",
      },
      {
        id: 67,
        price: "370K",
        name: "Spacious House in Kolkata 67",
        address: "777 Shoreline Avenue, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property67.jpg",
      },
      {
        id: 68,
        price: "390K",
        name: "Charming Home in Kolkata 68",
        address: "888 Coastal Lane, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
    ],
  },

  // Kolkata - 400K - 500K
  {
    propertyType: "House",
    location: "Kolkata",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 69,
        price: "420K",
        name: "Elegant House in Kolkata 69",
        address: "999 Seaside Road, Kolkata",
        beds: 5,
        bathroom: 4,
        area: "2500 sqft",
        image: "https://example.com/property69.jpg",
      },
      {
        id: 70,
        price: "450K",
        name: "Luxurious Home in Kolkata 70",
        address: "1010 Bay Lane, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2000 sqft",
        image: "https://example.com/property70.jpg",
      },
      {
        id: 71,
        price: "470K",
        name: "Spacious House in Kolkata 71",
        address: "1111 Oceanfront Avenue, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1800 sqft",
        image: "https://example.com/property71.jpg",
      },
      {
        id: 72,
        price: "490K",
        name: "Charming Home in Kolkata 72",
        address: "1212 Shoreline Lane, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "2200 sqft",
        image: "https://example.com/property72.jpg",
      },
    ],
  },
  // ...repeat for the "Flat" property type with the same structure
  // Delhi - 100K - 200K
  {
    propertyType: "Flat",
    location: "Delhi",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 1,
        price: "150K",
        name: "Cozy Flat in Delhi 1",
        address: "123 Main Street, Delhi",
        beds: 2,
        bathroom: 1,
        area: "800 sqft",
        image: "https://example.com/flat1.jpg",
      },
      {
        id: 2,
        price: "170K",
        name: "Modern Apartment in Delhi 2",
        address: "456 Park Avenue, Delhi",
        beds: 1,
        bathroom: 1,
        area: "650 sqft",
        image: "https://example.com/flat2.jpg",
      },
      {
        id: 3,
        price: "180K",
        name: "Charming Flat in Delhi 3",
        address: "789 Elm Street, Delhi",
        beds: 2,
        bathroom: 2,
        area: "900 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 4,
        price: "190K",
        name: "Stylish Apartment in Delhi 4",
        address: "101 Maple Avenue, Delhi",
        beds: 2,
        bathroom: 2,
        area: "850 sqft",
        image: "https://example.com/flat4.jpg",
      },
    ],
  },
  // Delhi - 200K - 300K
  {
    propertyType: "Flat",
    location: "Delhi",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 17,
        price: "220K",
        name: "Spacious House in Delhi 17",
        address: "234 Oak Lane, Delhi",
        beds: 4,
        bathroom: 2,
        area: "1600 sqft",
        image: "https://example.com/house17.jpg",
      },
      {
        id: 18,
        price: "250K",
        name: "Luxurious Home in Delhi 18",
        address: "567 Pine Street, Delhi",
        beds: 5,
        bathroom: 3,
        area: "1800 sqft",
        image: "https://example.com/house18.jpg",
      },
      {
        id: 19,
        price: "270K",
        name: "Spacious House in Delhi 19",
        address: "890 Cedar Road, Delhi",
        beds: 4,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/house19.jpg",
      },
      {
        id: 20,
        price: "290K",
        name: "Charming Home in Delhi 20",
        address: "123 Ivy Lane, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/house20.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Delhi - 300K - 400K
  {
    propertyType: "Flat",
    location: "Delhi",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 21,
        price: "320K",
        name: "Elegant House in Delhi 21",
        address: "234 Birch Street, Delhi",
        beds: 5,
        bathroom: 3,
        area: "2000 sqft",
        image:
          "https://images.unsplash.com/photo-1575517111478-7f6afd0973db?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MjB8fGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 22,
        price: "350K",
        name: "Luxury Home in Delhi 22",
        address: "567 Elm Lane, Delhi",
        beds: 4,
        bathroom: 3,
        area: "1800 sqft",
        image: "https://example.com/house22.jpg",
      },
      {
        id: 23,
        price: "370K",
        name: "Spacious House in Delhi 23",
        address: "890 Oak Lane, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/house23.jpg",
      },
      {
        id: 24,
        price: "390K",
        name: "Charming Home in Delhi 24",
        address: "123 Pine Street, Delhi",
        beds: 4,
        bathroom: 3,
        area: "1700 sqft",
        image: "https://example.com/house24.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Delhi - 400K - 500K
  {
    propertyType: "Flat",
    location: "Delhi",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 25,
        price: "420K",
        name: "Elegant House in Delhi 25",
        address: "234 Cedar Road, Delhi",
        beds: 4,
        bathroom: 3,
        area: "1800 sqft",
        image:
          "https://plus.unsplash.com/premium_photo-1664267475555-d0f774fc534a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmxhdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 26,
        price: "450K",
        name: "Luxury Home in Delhi 26",
        address: "567 Ivy Lane, Delhi",
        beds: 5,
        bathroom: 4,
        area: "2200 sqft",
        image: "https://example.com/house26.jpg",
      },
      {
        id: 27,
        price: "470K",
        name: "Spacious House in Delhi 27",
        address: "890 Pine Street, Delhi",
        beds: 4,
        bathroom: 3,
        area: "1900 sqft",
        image: "https://example.com/house27.jpg",
      },
      {
        id: 28,
        price: "490K",
        name: "Charming Home in Delhi 28",
        address: "123 Elm Lane, Delhi",
        beds: 3,
        bathroom: 2,
        area: "1600 sqft",
        image: "https://example.com/house28.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // ... repeat for other price ranges in Delhi

  // Mumbai - 100K - 200K
  {
    propertyType: "Flat",
    location: "Mumbai",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 9,
        price: "120K",
        name: "Compact Flat in Mumbai 1",
        address: "123 Sea View Road, Mumbai",
        beds: 1,
        bathroom: 1,
        area: "600 sqft",
        image: "https://example.com/flat9.jpg",
      },
      {
        id: 10,
        price: "180K",
        name: "Modern Apartment in Mumbai 2",
        address: "456 Palm Avenue, Mumbai",
        beds: 2,
        bathroom: 1,
        area: "800 sqft",
        image: "https://example.com/flat10.jpg",
      },
      {
        id: 11,
        price: "160K",
        name: "Cozy Flat in Mumbai 3",
        address: "789 Shoreline Drive, Mumbai",
        beds: 1,
        bathroom: 1,
        area: "700 sqft",
        image:
          "https://plus.unsplash.com/premium_photo-1664267475555-d0f774fc534a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmxhdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 12,
        price: "190K",
        name: "Charming Apartment in Mumbai 4",
        address: "101 Sunset Blvd, Mumbai",
        beds: 2,
        bathroom: 2,
        area: "850 sqft",
        image: "https://example.com/flat12.jpg",
      },
    ],
  },
  // Mumbai - 200K - 300K
  {
    propertyType: "Flat",
    location: "Mumbai",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 29,
        price: "220K",
        name: "Cozy Home in Mumbai 29",
        address: "234 Ocean View, Mumbai",
        beds: 2,
        bathroom: 1,
        area: "1000 sqft",
        image: "https://example.com/mumbai29.jpg",
      },
      {
        id: 30,
        price: "240K",
        name: "Charming House in Mumbai 30",
        address: "567 Beach Road, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1200 sqft",
        image: "https://example.com/mumbai30.jpg",
      },
      {
        id: 31,
        price: "260K",
        name: "Spacious Home in Mumbai 31",
        address: "890 Coastal Avenue, Mumbai",
        beds: 2,
        bathroom: 1,
        area: "1100 sqft",
        image: "https://example.com/mumbai31.jpg",
      },
      {
        id: 32,
        price: "280K",
        name: "Elegant House in Mumbai 32",
        address: "123 Seaside Drive, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1300 sqft",
        image: "https://example.com/mumbai32.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Mumbai - 300K - 400K
  {
    propertyType: "Flat",
    location: "Mumbai",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 33,
        price: "320K",
        name: "Luxurious Home in Mumbai 33",
        address: "234 Sunset Boulevard, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "1600 sqft",
        image: "https://example.com/mumbai33.jpg",
      },
      {
        id: 34,
        price: "340K",
        name: "Modern House in Mumbai 34",
        address: "567 Oceanfront Avenue, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/mumbai34.jpg",
      },
      {
        id: 35,
        price: "360K",
        name: "Spacious Home in Mumbai 35",
        address: "890 Beachside Drive, Mumbai",
        beds: 4,
        bathroom: 2,
        area: "1500 sqft",
        image:
          "https://plus.unsplash.com/premium_photo-1664267475555-d0f774fc534a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmxhdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 36,
        price: "380K",
        name: "Charming House in Mumbai 36",
        address: "123 Coastal Lane, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/mumbai36.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Mumbai - 400K - 500K
  {
    propertyType: "Flat",
    location: "Mumbai",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 37,
        price: "420K",
        name: "Elegant Home in Mumbai 37",
        address: "234 Sea View, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/mumbai37.jpg",
      },
      {
        id: 38,
        price: "440K",
        name: "Luxury House in Mumbai 38",
        address: "567 Beachfront Avenue, Mumbai",
        beds: 4,
        bathroom: 3,
        area: "1700 sqft",
        image:
          "https://plus.unsplash.com/premium_photo-1664267475555-d0f774fc534a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MXx8ZmxhdHN8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=500&q=60",
      },
      {
        id: 39,
        price: "460K",
        name: "Spacious Home in Mumbai 39",
        address: "890 Shoreline Drive, Mumbai",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/mumbai39.jpg",
      },
      {
        id: 40,
        price: "480K",
        name: "Charming House in Mumbai 40",
        address: "123 Beach Lane, Mumbai",
        beds: 2,
        bathroom: 1,
        area: "1200 sqft",
        image: "https://example.com/mumbai40.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Chennai - 100K - 200K
  {
    propertyType: "Flat",
    location: "Chennai",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 17,
        price: "180K",
        name: "Modern Flat in Chennai 1",
        address: "123 Marina Street, Chennai",
        beds: 2,
        bathroom: 1,
        area: "750 sqft",
        image: "https://example.com/flat17.jpg",
      },
      {
        id: 18,
        price: "190K",
        name: "Charming Apartment in Chennai 2",
        address: "456 Garden Lane, Chennai",
        beds: 1,
        bathroom: 1,
        area: "600 sqft",
        image: "https://example.com/flat18.jpg",
      },
      {
        id: 19,
        price: "150K",
        name: "Cozy Flat in Chennai 3",
        address: "789 Oasis Road, Chennai",
        beds: 1,
        bathroom: 1,
        area: "700 sqft",
        image: "https://example.com/flat19.jpg",
      },
      {
        id: 20,
        price: "170K",
        name: "Stylish Apartment in Chennai 4",
        address: "101 Lotus Street, Chennai",
        beds: 2,
        bathroom: 1,
        area: "650 sqft",
        image: "https://example.com/flat20.jpg",
      },
    ],
  },

  // Chennai - 200K - 300K
  {
    propertyType: "Flat",
    location: "Chennai",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 41,
        price: "220K",
        name: "Cozy Home in Chennai 41",
        address: "234 Palm Street, Chennai",
        beds: 2,
        bathroom: 1,
        area: "1000 sqft",
        image: "https://example.com/chennai41.jpg",
      },
      {
        id: 42,
        price: "240K",
        name: "Charming House in Chennai 42",
        address: "567 Garden Road, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1200 sqft",
        image: "https://example.com/chennai42.jpg",
      },
      {
        id: 43,
        price: "260K",
        name: "Spacious Home in Chennai 43",
        address: "890 Blossom Avenue, Chennai",
        beds: 2,
        bathroom: 1,
        area: "1100 sqft",
        image: "https://example.com/chennai43.jpg",
      },
      {
        id: 44,
        price: "280K",
        name: "Elegant House in Chennai 44",
        address: "123 Flower Lane, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1300 sqft",
        image: "https://example.com/chennai44.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Chennai - 300K - 400K
  {
    propertyType: "Flat",
    location: "Chennai",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 45,
        price: "320K",
        name: "Luxurious Home in Chennai 45",
        address: "234 Orchard Avenue, Chennai",
        beds: 4,
        bathroom: 3,
        area: "1600 sqft",
        image: "https://example.com/chennai45.jpg",
      },
      {
        id: 46,
        price: "340K",
        name: "Modern House in Chennai 46",
        address: "567 Park Street, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/chennai46.jpg",
      },
      {
        id: 47,
        price: "360K",
        name: "Spacious Home in Chennai 47",
        address: "890 Green Lane, Chennai",
        beds: 4,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/chennai47.jpg",
      },
      {
        id: 48,
        price: "380K",
        name: "Charming House in Chennai 48",
        address: "123 Meadow Road, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/chennai48.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Chennai - 400K - 500K
  {
    propertyType: "Flat",
    location: "Chennai",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 49,
        price: "420K",
        name: "Elegant Home in Chennai 49",
        address: "234 Forest Lane, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/chennai49.jpg",
      },
      {
        id: 50,
        price: "440K",
        name: "Luxury House in Chennai 50",
        address: "567 Woodland Avenue, Chennai",
        beds: 4,
        bathroom: 3,
        area: "1700 sqft",
        image: "https://example.com/chennai50.jpg",
      },
      {
        id: 51,
        price: "460K",
        name: "Spacious Home in Chennai 51",
        address: "890 Grove Street, Chennai",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/chennai51.jpg",
      },
      {
        id: 52,
        price: "480K",
        name: "Charming House in Chennai 52",
        address: "123 Park Lane, Chennai",
        beds: 2,
        bathroom: 1,
        area: "1200 sqft",
        image: "https://example.com/chennai52.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // ... repeat for other price ranges in Chennai

  // Kolkata - 100K - 200K
  {
    propertyType: "Flat",
    location: "Kolkata",
    priceRange: "100K - 200K",
    properties: [
      {
        id: 25,
        price: "140K",
        name: "Charming Apartment in Kolkata 1",
        address: "123 Garden Road, Kolkata",
        beds: 1,
        bathroom: 1,
        area: "650 sqft",
        image: "https://example.com/flat25.jpg",
      },
      {
        id: 26,
        price: "160K",
        name: "Modern Flat in Kolkata 2",
        address: "456 Park Street, Kolkata",
        beds: 2,
        bathroom: 1,
        area: "750 sqft",
        image: "https://example.com/flat26.jpg",
      },
      {
        id: 27,
        price: "180K",
        name: "Stylish Apartment in Kolkata 3",
        address: "789 Lake View, Kolkata",
        beds: 2,
        bathroom: 2,
        area: "800 sqft",
        image: "https://example.com/flat27.jpg",
      },
      {
        id: 28,
        price: "190K",
        name: "Cozy Flat in Kolkata 4",
        address: "101 Riverside Drive, Kolkata",
        beds: 1,
        bathroom: 1,
        area: "700 sqft",
        image: "https://example.com/flat28.jpg",
      },
    ],
  },
  // Kolkata - 200K - 300K
  {
    propertyType: "Flat",
    location: "Kolkata",
    priceRange: "200K - 300K",
    properties: [
      {
        id: 53,
        price: "220K",
        name: "Cozy Home in Kolkata 53",
        address: "234 Palm Street, Kolkata",
        beds: 2,
        bathroom: 1,
        area: "1000 sqft",
        image: "https://example.com/kolkata53.jpg",
      },
      {
        id: 54,
        price: "240K",
        name: "Charming House in Kolkata 54",
        address: "567 Garden Road, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1200 sqft",
        image: "https://example.com/kolkata54.jpg",
      },
      {
        id: 55,
        price: "260K",
        name: "Spacious Home in Kolkata 55",
        address: "890 Blossom Avenue, Kolkata",
        beds: 2,
        bathroom: 1,
        area: "1100 sqft",
        image: "https://example.com/kolkata55.jpg",
      },
      {
        id: 56,
        price: "280K",
        name: "Elegant House in Kolkata 56",
        address: "123 Flower Lane, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1300 sqft",
        image: "https://example.com/kolkata56.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Kolkata - 300K - 400K
  {
    propertyType: "Flat",
    location: "Kolkata",
    priceRange: "300K - 400K",
    properties: [
      {
        id: 57,
        price: "320K",
        name: "Luxurious Home in Kolkata 57",
        address: "234 Orchard Avenue, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "1600 sqft",
        image: "https://example.com/kolkata57.jpg",
      },
      {
        id: 58,
        price: "340K",
        name: "Modern House in Kolkata 58",
        address: "567 Park Street, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/kolkata58.jpg",
      },
      {
        id: 59,
        price: "360K",
        name: "Spacious Home in Kolkata 59",
        address: "890 Green Lane, Kolkata",
        beds: 4,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/kolkata59.jpg",
      },
      {
        id: 60,
        price: "380K",
        name: "Charming House in Kolkata 60",
        address: "123 Meadow Road, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/kolkata60.jpg",
      },
      // ... repeat for other properties
    ],
  },

  // Kolkata - 400K - 500K
  {
    propertyType: "Flat",
    location: "Kolkata",
    priceRange: "400K - 500K",
    properties: [
      {
        id: 61,
        price: "420K",
        name: "Elegant Home in Kolkata 61",
        address: "234 Forest Lane, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1400 sqft",
        image: "https://example.com/kolkata61.jpg",
      },
      {
        id: 62,
        price: "440K",
        name: "Luxury House in Kolkata 62",
        address: "567 Woodland Avenue, Kolkata",
        beds: 4,
        bathroom: 3,
        area: "1700 sqft",
        image: "https://example.com/kolkata62.jpg",
      },
      {
        id: 63,
        price: "460K",
        name: "Spacious Home in Kolkata 63",
        address: "890 Grove Street, Kolkata",
        beds: 3,
        bathroom: 2,
        area: "1500 sqft",
        image: "https://example.com/kolkata63.jpg",
      },
      {
        id: 64,
        price: "480K",
        name: "Charming House in Kolkata 64",
        address: "123 Park Lane, Kolkata",
        beds: 2,
        bathroom: 1,
        area: "1200 sqft",
        image: "https://example.com/kolkata64.jpg",
      },
      // ... repeat for other properties
    ],
  },
];
